#!/usr/bin/env python
# -*- coding: utf-8 -*-

from __future__ import print_function

import argparse
from argparse import RawTextHelpFormatter

parser = argparse.ArgumentParser(description="""
Converts D'ni sentences or numbers between different romanization systems.

EITHER enter a sentence OR a number, the program cannot parse both at the same
time, UNLESS between Dnifont and UCSUR. Examples:

dniroman.py ".khahpo rehzuhnuh rildolgehlehnij gahth"
Dnifont:  .kapo rezunu rilDolgelenij gaT
NTS:      .xapo rezunu rildolgelenij gaþ
LTS:      .khapo rezunu rildolgelenij gath
RTS:      .khahpo rezunu rildolgelenij gahth
UCSUR:       

dniroman.py -b "[10|15|20]"
Dnifont:  )%[
Alphanum:  AFK
""", formatter_class=RawTextHelpFormatter)

parser.add_argument("-x", "--names", help="Also fix common spellings, e.g. Kadish -> Kaydish", action="store_true")
parser.add_argument("phrase", help="input is Old Transliteration Standard (default)", type=str, action="store")
format = parser.add_mutually_exclusive_group()
format.add_argument("-n", "--nts", help="input is New Transliteration Standard", action="store_true")
format.add_argument("-f", "--dfont", help="input is Dnifont / RAWA's transliteration", action="store_true")
format.add_argument("-l", "--lts", help="input is Larry's Transliteration Standard", action="store_true")
format.add_argument("-r", "--rts", help="input is Revised Transliteration Standard", action="store_true")
format.add_argument("-u", "--ucsur", help="Under-ConScript Unicode Registry", action="store_true")
format.add_argument("-b", "--brack", help="Digits as brackets: \"[10|11|12]\"", action="store_true")
format.add_argument("-d", "--nfont", help="Digits as Dnifont: \")!@\"", action="store_true")
format.add_argument("-a", "--alpha", help="Digits as alphanumeric: \"ABC\"", action="store_true")
args = parser.parse_args()



def ots2nts(in_ots):
    out_nts = in_ots.replace(u"ch", u"ç")
    out_nts = out_nts.replace(u"Ch", u"Ç")
    out_nts = out_nts.replace(u"CH", u"Ç")
    out_nts = out_nts.replace(u"ts", u"c")
    out_nts = out_nts.replace(u"Ts", u"C")
    out_nts = out_nts.replace(u"TS", u"C")
    out_nts = out_nts.replace(u"kh", u"x")
    out_nts = out_nts.replace(u"Kh", u"X")
    out_nts = out_nts.replace(u"KH", u"X")
    out_nts = out_nts.replace(u"dh", u"ð")
    out_nts = out_nts.replace(u"Dh", u"Ð")
    out_nts = out_nts.replace(u"DH", u"Ð")
    out_nts = out_nts.replace(u"sh", u"š")
    out_nts = out_nts.replace(u"Sh", u"Š")
    out_nts = out_nts.replace(u"SH", u"Š")
    out_nts = out_nts.replace(u"th", u"þ")
    out_nts = out_nts.replace(u"Th", u"Þ")
    out_nts = out_nts.replace(u"TH", u"Þ")
    out_nts = out_nts.replace(u"ih", u"i")
    out_nts = out_nts.replace(u"Ih", u"I")
    out_nts = out_nts.replace(u"IH", u"I")
    out_nts = out_nts.replace(u"í", u"á")
    out_nts = out_nts.replace(u"Í", u"Á")
    out_nts = out_nts.replace(u"ay", u"é")
    out_nts = out_nts.replace(u"Ay", u"É")
    out_nts = out_nts.replace(u"AY", u"É")
    out_nts = out_nts.replace(u"ai", u"é")
    out_nts = out_nts.replace(u"Ai", u"É")
    out_nts = out_nts.replace(u"AI", u"É")
    out_nts = out_nts.replace(u"ee", u"í")
    out_nts = out_nts.replace(u"Ee", u"Í")
    out_nts = out_nts.replace(u"EE", u"Í")
    out_nts = out_nts.replace(u"oy", u"ó")
    out_nts = out_nts.replace(u"Oy", u"Ó")
    out_nts = out_nts.replace(u"OY", u"Ó")
    out_nts = out_nts.replace(u"oo", u"ú")
    out_nts = out_nts.replace(u"Oo", u"Ú")
    out_nts = out_nts.replace(u"OO", u"Ú")
    out_nts = out_nts.replace(u"å", u"æ")
    out_nts = out_nts.replace(u"Å", u"Æ")
    out_nts = out_nts.replace(u"a", u"æ")
    out_nts = out_nts.replace(u"A", u"Æ")
    out_nts = out_nts.replace(u"æh", u"ah")
    out_nts = out_nts.replace(u"Æh", u"AH")
    out_nts = out_nts.replace(u"ÆH", u"AH")
    out_nts = out_nts.replace(u"ah", u"a")
    out_nts = out_nts.replace(u"Ah", u"A")
    out_nts = out_nts.replace(u"AH", u"A")
    out_nts = out_nts.replace(u"eh", u"e")
    out_nts = out_nts.replace(u"Eh", u"E")
    out_nts = out_nts.replace(u"EH", u"E")
    out_nts = out_nts.replace(u"uh", u"u")
    out_nts = out_nts.replace(u"Uh", u"U")
    out_nts = out_nts.replace(u"UH", u"U")
    if args.names:
        out_nts = out_nts.replace(u"Æe'guræ", u"Æ'gura")
        out_nts = out_nts.replace(u"Æe’guræ", u"Æ’gura")
        out_nts = out_nts.replace(u"ÆE'GURÆ", u"Æ'GURA")
        out_nts = out_nts.replace(u"ÆE’GURÆ", u"Æ’GURA")
        out_nts = out_nts.replace(u"Aitrus", u"Étrus")
        out_nts = out_nts.replace(u"AITRUS", u"ÉTRUS")
        out_nts = out_nts.replace(u"Ætrus", u"Étrus")
        out_nts = out_nts.replace(u"ÆTRUS", u"ÉTRUS")
        out_nts = out_nts.replace(u"cænnen", u"kænen")
        out_nts = out_nts.replace(u"Cænnen", u"Kænen")
        out_nts = out_nts.replace(u"CÆNNEN", u"KÆNEN")
        out_nts = out_nts.replace(u"D'ni", u"D'ní")
        out_nts = out_nts.replace(u"D'NI", u"D'NÍ")
        out_nts = out_nts.replace(u"D’ni", u"D’ní")
        out_nts = out_nts.replace(u"D’NI", u"D’NÍ")
        out_nts = out_nts.replace(u"Ghen", u"Gen")
        out_nts = out_nts.replace(u"GHEN", u"GEN")
        out_nts = out_nts.replace(u"Er'cænæ", u"Er'kana")
        out_nts = out_nts.replace(u"ER'CÆNÆ", u"ER'KANA")
        out_nts = out_nts.replace(u"Er’cænæ", u"Er’kana")
        out_nts = out_nts.replace(u"ER’CÆNÆ", u"ER’KANA")
        out_nts = out_nts.replace(u"Giræ", u"Gira")
        out_nts = out_nts.replace(u"GIRÆ", u"GIRA")
        out_nts = out_nts.replace(u"Jælæk", u"Jalak")
        out_nts = out_nts.replace(u"JÆLÆK", u"JALAK")
        out_nts = out_nts.replace(u"Kædiš", u"Kédiš")
        out_nts = out_nts.replace(u"KÆDIŠ", u"KÉDIŠ")
        out_nts = out_nts.replace(u"Kemo", u"Kímo")
        out_nts = out_nts.replace(u"KEMO", u"KÍMO")
        out_nts = out_nts.replace(u"Minkætæ", u"Minkata")
        out_nts = out_nts.replace(u"MINKÆTÆ", u"MINKATA")
        out_nts = out_nts.replace(u"Tolesæ", u"Tolesa")
        out_nts = out_nts.replace(u"TOLESÆ", u"TOLESA")
        out_nts = out_nts.replace(u"Tomænæ", u"Tomana")
        out_nts = out_nts.replace(u"TOMÆNÆ", u"TOMANA")
        out_nts = out_nts.replace(u"Tomæn", u"Toman")
        out_nts = out_nts.replace(u"TOMÆN", u"TOMAN")
        out_nts = out_nts.replace(u"Cogæl", u"Cogal")
        out_nts = out_nts.replace(u"COGÆL", u"COGAL")
        out_nts = out_nts.replace(u"whærk", u"wark")
        out_nts = out_nts.replace(u"Whærk", u"Wark")
        out_nts = out_nts.replace(u"WHÆRK", u"WARK")
        out_nts = out_nts.replace(u"Yíšæ", u"Yíša")
        out_nts = out_nts.replace(u"YÍŠÆ", u"YÍŠA")
    return out_nts

def nts2ots(in_nts):
    out_ots = in_nts.replace(u"a", u"ah")
    out_ots = out_ots.replace(u"A", u"Ah")
    out_ots = out_ots.replace(u"e", u"eh")
    out_ots = out_ots.replace(u"E", u"Eh")
    out_ots = out_ots.replace(u"é", u"ay")
    out_ots = out_ots.replace(u"É", u"Ay")
    out_ots = out_ots.replace(u"í", u"ee")
    out_ots = out_ots.replace(u"Í", u"Ee")
    out_ots = out_ots.replace(u"ó", u"oy")
    out_ots = out_ots.replace(u"Ó", u"Oy")
    out_ots = out_ots.replace(u"ú", u"oo")
    out_ots = out_ots.replace(u"Ú", u"Oo")
    out_ots = out_ots.replace(u"á", u"í")
    out_ots = out_ots.replace(u"Á", u"Í")
    out_ots = out_ots.replace(u"æ", u"a")
    out_ots = out_ots.replace(u"Æ", u"A")
    out_ots = out_ots.replace(u"c", u"ts")
    out_ots = out_ots.replace(u"C", u"Ts")
    out_ots = out_ots.replace(u"ç", u"ch")
    out_ots = out_ots.replace(u"Ç", u"Ch")
    out_ots = out_ots.replace(u"š", u"sh")
    out_ots = out_ots.replace(u"Š", u"Sh")
    out_ots = out_ots.replace(u"þ", u"th")
    out_ots = out_ots.replace(u"Þ", u"Th")
    out_ots = out_ots.replace(u"ð", u"dh")
    out_ots = out_ots.replace(u"Ð", u"Dh")
    out_ots = out_ots.replace(u"x", u"kh")
    out_ots = out_ots.replace(u"X", u"Kh")
    out_ots = out_ots.replace(u"eheh", u"ee")
    out_ots = out_ots.replace(u"EhEh", u"Ee")
    if args.names:
        out_ots = out_ots.replace(u"aheh'gurah", u"A'gurah")
        out_ots = out_ots.replace(u"Aheh'gurah", u"A'gurah")
        out_ots = out_ots.replace(u"AhEh'GURAh", u"A'GURAH")
        out_ots = out_ots.replace(u"aheh’gurah", u"A’gurah")
        out_ots = out_ots.replace(u"Aheh’gurah", u"A’gurah")
        out_ots = out_ots.replace(u"AhEh’GURAh", u"A’GURAH")
        out_ots = out_ots.replace(u"ahitrus", u"Aytrus")
        out_ots = out_ots.replace(u"Ahitrus", u"Aytrus")
        out_ots = out_ots.replace(u"AhITRUS", u"AYTRUS")
        out_ots = out_ots.replace(u"ahtrus", u"Aytrus")
        out_ots = out_ots.replace(u"Ahtrus", u"Aytrus")
        out_ots = out_ots.replace(u"AhTRUS", u"AYTRUS")
        out_ots = out_ots.replace(u"tsahnnehn", u"kanehn")
        out_ots = out_ots.replace(u"Tsahnnehn", u"Kanehn")
        out_ots = out_ots.replace(u"TsAhNNEhN", u"KANEHN")
        out_ots = out_ots.replace(u"d'ni", u"D'nee")
        out_ots = out_ots.replace(u"D'ni", u"D'nee")
        out_ots = out_ots.replace(u"D'NI", u"D'NEE")
        out_ots = out_ots.replace(u"ghehn", u"Gehn")
        out_ots = out_ots.replace(u"Ghehn", u"Gehn")
        out_ots = out_ots.replace(u"GHEhN", u"GEHN")
        out_ots = out_ots.replace(u"ehr'tsahnah", u"Ehr'kahnah")
        out_ots = out_ots.replace(u"Ehr'tsahnah", u"Ehr'kahnah")
        out_ots = out_ots.replace(u"EhR'TsAhNAh", u"EHR'KAHNAH")
        out_ots = out_ots.replace(u"ehr’tsahnah", u"Ehr’kahnah")
        out_ots = out_ots.replace(u"Ehr’tsahnah", u"Ehr’kahnah")
        out_ots = out_ots.replace(u"EhR’TsAhNAh", u"EHR’KAHNAH")
        out_ots = out_ots.replace(u"girah", u"Girah")
        out_ots = out_ots.replace(u"GIRAh", u"GIRAH")
        out_ots = out_ots.replace(u"jahlahk", u"Jahlahk")
        out_ots = out_ots.replace(u"JAhLAhK", u"JAHLAHK")
        out_ots = out_ots.replace(u"kahdish", u"Kaydish")
        out_ots = out_ots.replace(u"Kadish", u"Kaydish")
        out_ots = out_ots.replace(u"KAhDISH", u"KAYDISH")
        out_ots = out_ots.replace(u"kehmo", u"Keemo")
        out_ots = out_ots.replace(u"Kehmo", u"Keemo")
        out_ots = out_ots.replace(u"KEhMO", u"KEEMO")
        out_ots = out_ots.replace(u"minkahtah", u"Minkahtah")
        out_ots = out_ots.replace(u"MINKAhTAh", u"MINKAHTAH")
        out_ots = out_ots.replace(u"tolehsah", u"Tolehsah")
        out_ots = out_ots.replace(u"TOLEhSAh", u"TOLEHSAH")
        out_ots = out_ots.replace(u"tomahnah", u"Tomahnah")
        out_ots = out_ots.replace(u"TOMAhNAh", u"TOMAHNAH")
        out_ots = out_ots.replace(u"tomahn", u"Tomahn")
        out_ots = out_ots.replace(u"TOMAhN", u"TOMAHN")
        out_ots = out_ots.replace(u"tsogahl", u"Tsogahl")
        out_ots = out_ots.replace(u"TSOGAhL", u"TSOGAHL")
        out_ots = out_ots.replace(u"whahrk", u"wahrk")
        out_ots = out_ots.replace(u"Whahrk", u"Wahrk")
        out_ots = out_ots.replace(u"WHAhRK", u"WAHRK")
        out_ots = out_ots.replace(u"yeeshah", u"Yeeshah")
        out_ots = out_ots.replace(u"YEeSHAh", u"YEESHAH")
    return out_ots

def nts2dfont(in_nts):
    out_dfont = in_nts.replace(u"æ", u"å")
    out_dfont = out_dfont.replace(u"ú", u"U")
    out_dfont = out_dfont.replace(u"ó", u"O")
    out_dfont = out_dfont.replace(u"í", u"E")
    out_dfont = out_dfont.replace(u"é", u"A")
    out_dfont = out_dfont.replace(u"á", u"I")
    out_dfont = out_dfont.replace(u"þ", u"T")
    out_dfont = out_dfont.replace(u"š", u"S")
    out_dfont = out_dfont.replace(u"d", u"D")
    out_dfont = out_dfont.replace(u"ð", u"d")
    out_dfont = out_dfont.replace(u"k", u"K")
    out_dfont = out_dfont.replace(u"x", u"k")
    out_dfont = out_dfont.replace(u"c", u"x")
    out_dfont = out_dfont.replace(u"ç", u"c")
    if args.names:
        out_dfont = out_dfont.replace(u"ae'gura", u"å'gura")
        out_dfont = out_dfont.replace(u"ae’gura", u"å'gura")
        out_dfont = out_dfont.replace(u"aitrus", u"Atrus")
        out_dfont = out_dfont.replace(u"atrus", u"Atrus")
        out_dfont = out_dfont.replace(u"xannen", u"kånen")
        out_dfont = out_dfont.replace(u"D'ni", u"D'nE")
        out_dfont = out_dfont.replace(u"D’ni", u"D’nE")
        out_dfont = out_dfont.replace(u"ghen", u"gen")
        out_dfont = out_dfont.replace(u"er'xana", u"er'Kana")
        out_dfont = out_dfont.replace(u"er’xana", u"er'Kana")
        out_dfont = out_dfont.replace(u"KaDish", u"KADiS")
        out_dfont = out_dfont.replace(u"Kemo", u"KEmo")
        out_dfont = out_dfont.replace(u"tsogal", u"xogal")
        out_dfont = out_dfont.replace(u"wharK", u"warK")
        out_dfont = out_dfont.replace(u"yeesha", u"yESa")
    return out_dfont

def dfont2nts(in_dfont):
    out_nts = in_dfont.replace(u"c", u"ç")
    out_nts = out_nts.replace(u"x", u"c")
    out_nts = out_nts.replace(u"k", u"x")
    out_nts = out_nts.replace(u"K", u"k")
    out_nts = out_nts.replace(u"d", u"ð")
    out_nts = out_nts.replace(u"D", u"d")
    out_nts = out_nts.replace(u"S", u"š")
    out_nts = out_nts.replace(u"T", u"þ")
    out_nts = out_nts.replace(u"I", u"á")
    out_nts = out_nts.replace(u"A", u"é")
    out_nts = out_nts.replace(u"E", u"í")
    out_nts = out_nts.replace(u"O", u"ó")
    out_nts = out_nts.replace(u"U", u"ú")
    out_nts = out_nts.replace(u"å", u"æ")
    return out_nts

def nts2lts(in_nts):
    out_lts = in_nts.replace(u"æ", u"å")
    out_lts = out_lts.replace(u"Æ", u"Å")
    out_lts = out_lts.replace(u"ú", u"ū")
    out_lts = out_lts.replace(u"Ú", u"Ū")
    out_lts = out_lts.replace(u"ó", u"oy")
    out_lts = out_lts.replace(u"Ó", u"Oy")
    out_lts = out_lts.replace(u"í", u"ē")
    out_lts = out_lts.replace(u"Í", u"Ē")
    out_lts = out_lts.replace(u"é", u"ā")
    out_lts = out_lts.replace(u"É", u"Ā")
    out_lts = out_lts.replace(u"á", u"ī")
    out_lts = out_lts.replace(u"Á", u"Ī")
    out_lts = out_lts.replace(u"þ", u"th")
    out_lts = out_lts.replace(u"Þ", u"Th")
    out_lts = out_lts.replace(u"š", u"sh")
    out_lts = out_lts.replace(u"Š", u"Sh")
    out_lts = out_lts.replace(u"ð", u"dh")
    out_lts = out_lts.replace(u"Ð", u"Dh")
    out_lts = out_lts.replace(u"x", u"kh")
    out_lts = out_lts.replace(u"X", u"Kh")
    out_lts = out_lts.replace(u"c", u"ts")
    out_lts = out_lts.replace(u"C", u"Ts")
    out_lts = out_lts.replace(u"ç", u"ch")
    out_lts = out_lts.replace(u"Ç", u"Ch")
    if args.names:
        out_lts = out_lts.replace(u"ae'gura", u"Å'gura")
        out_lts = out_lts.replace(u"Ae'gura", u"Å'gura")
        out_lts = out_lts.replace(u"AE'GURA", u"Å'GURA")
        out_lts = out_lts.replace(u"ae’gura", u"Å’gura")
        out_lts = out_lts.replace(u"Ae’gura", u"Å’gura")
        out_lts = out_lts.replace(u"AE’GURA", u"Å’GURA")
        out_lts = out_lts.replace(u"aitrus", u"Ātrus")
        out_lts = out_lts.replace(u"Aitrus", u"Ātrus")
        out_lts = out_lts.replace(u"AITRUS", u"ĀTRUS")
        out_lts = out_lts.replace(u"atrus", u"Ātrus")
        out_lts = out_lts.replace(u"Atrus", u"Ātrus")
        out_lts = out_lts.replace(u"ATRUS", u"ĀTRUS")
        out_lts = out_lts.replace(u"tsannen", u"kånen")
        out_lts = out_lts.replace(u"Tsannen", u"Kånen")
        out_lts = out_lts.replace(u"TsANNEN", u"KÅNEN")
        out_lts = out_lts.replace(u"d'ni", u"D'nē")
        out_lts = out_lts.replace(u"D'ni", u"D'nē")
        out_lts = out_lts.replace(u"D'NI", u"D'NĒ")
        out_lts = out_lts.replace(u"d’ni", u"D’nē")
        out_lts = out_lts.replace(u"D’ni", u"D’nē")
        out_lts = out_lts.replace(u"D’NI", u"D’NĒ")
        out_lts = out_lts.replace(u"ghen", u"Gen")
        out_lts = out_lts.replace(u"Ghen", u"Gen")
        out_lts = out_lts.replace(u"GHEN", u"GEN")
        out_lts = out_lts.replace(u"er'tsana", u"Er'kana")
        out_lts = out_lts.replace(u"Er'tsana", u"Er'kana")
        out_lts = out_lts.replace(u"ER'TsANA", u"ER'KANA")
        out_lts = out_lts.replace(u"er’tsana", u"Er’kana")
        out_lts = out_lts.replace(u"Er’tsana", u"Er’kana")
        out_lts = out_lts.replace(u"ER’TsANA", u"ER’KANA")
        out_lts = out_lts.replace(u"kadish", u"Kādish")
        out_lts = out_lts.replace(u"Kadish", u"Kādish")
        out_lts = out_lts.replace(u"KADISH", u"KĀDISH")
        out_lts = out_lts.replace(u"kemo", u"Kēmo")
        out_lts = out_lts.replace(u"Kemo", u"Kēmo")
        out_lts = out_lts.replace(u"KEMO", u"KĒMO")
        out_lts = out_lts.replace(u"tomana", u"Tomana")
        out_lts = out_lts.replace(u"tsogal", u"Tsogal")
        out_lts = out_lts.replace(u"whark", u"wark")
        out_lts = out_lts.replace(u"Whark", u"Wark")
        out_lts = out_lts.replace(u"WHARK", u"WARK")
        out_lts = out_lts.replace(u"yeesha", u"Yēsha")
        out_lts = out_lts.replace(u"Yeesha", u"Yēsha")
        out_lts = out_lts.replace(u"YEESHA", u"YĒSHA")
    return out_lts

def lts2nts(lts):
    out_nts = lts.replace(u"ch", u"ç")
    out_nts = out_nts.replace(u"Ch", u"Ç")
    out_nts = out_nts.replace(u"CH", u"Ç")
    out_nts = out_nts.replace(u"ʦ", u"c")
    out_nts = out_nts.replace(u"ʦ", u"C")
    out_nts = out_nts.replace(u"ts", u"c")
    out_nts = out_nts.replace(u"Ts", u"C")
    out_nts = out_nts.replace(u"TS", u"C")
    out_nts = out_nts.replace(u"kh", u"x")
    out_nts = out_nts.replace(u"Kh", u"X")
    out_nts = out_nts.replace(u"KH", u"X")
    out_nts = out_nts.replace(u"dh", u"ð")
    out_nts = out_nts.replace(u"Dh", u"Ð")
    out_nts = out_nts.replace(u"DH", u"Ð")
    out_nts = out_nts.replace(u"sh", u"š")
    out_nts = out_nts.replace(u"Sh", u"Š")
    out_nts = out_nts.replace(u"SH", u"Š")
    out_nts = out_nts.replace(u"th", u"þ")
    out_nts = out_nts.replace(u"Th", u"Þ")
    out_nts = out_nts.replace(u"TH", u"Þ")
    out_nts = out_nts.replace(u"ī", u"á")
    out_nts = out_nts.replace(u"Ī", u"Á")
    out_nts = out_nts.replace(u"ā", u"é")
    out_nts = out_nts.replace(u"Ā", u"É")
    out_nts = out_nts.replace(u"ē", u"í")
    out_nts = out_nts.replace(u"Ē", u"Í")
    out_nts = out_nts.replace(u"oy", u"ó")
    out_nts = out_nts.replace(u"Oy", u"Ó")
    out_nts = out_nts.replace(u"OY", u"Ó")
    out_nts = out_nts.replace(u"ū", u"ú")
    out_nts = out_nts.replace(u"Ū", u"Ú")
    out_nts = out_nts.replace(u"å", u"æ")
    out_nts = out_nts.replace(u"Å", u"Æ")
    if args.names:
        out_nts = out_nts.replace(u"Ae'gura", u"Æ'gura")
        out_nts = out_nts.replace(u"Ae’gura", u"Æ’gura")
        out_nts = out_nts.replace(u"AE'GURA", u"Æ'GURA")
        out_nts = out_nts.replace(u"AE’GURA", u"Æ’GURA")
        out_nts = out_nts.replace(u"Aitrus", u"Étrus")
        out_nts = out_nts.replace(u"AITRUS", u"ÉTRUS")
        out_nts = out_nts.replace(u"Atrus", u"Étrus")
        out_nts = out_nts.replace(u"ATRUS", u"ÉTRUS")
        out_nts = out_nts.replace(u"cannen", u"kænen")
        out_nts = out_nts.replace(u"Cannen", u"Kænen")
        out_nts = out_nts.replace(u"CANNEN", u"KÆNEN")
        out_nts = out_nts.replace(u"D'ni", u"D'ní")
        out_nts = out_nts.replace(u"D'NI", u"D'NÍ")
        out_nts = out_nts.replace(u"D’ni", u"D’ní")
        out_nts = out_nts.replace(u"D’NI", u"D’NÍ")
        out_nts = out_nts.replace(u"Ghen", u"Gen")
        out_nts = out_nts.replace(u"GHEN", u"GEN")
        out_nts = out_nts.replace(u"Er'cana", u"Er'kana")
        out_nts = out_nts.replace(u"ER'CANA", u"ER'KANA")
        out_nts = out_nts.replace(u"Er’cana", u"Er’kana")
        out_nts = out_nts.replace(u"ER’CANA", u"ER’KANA")
        out_nts = out_nts.replace(u"Kadiš", u"Kédiš")
        out_nts = out_nts.replace(u"KADIŠ", u"KÉDIŠ")
        out_nts = out_nts.replace(u"Kemo", u"Kímo")
        out_nts = out_nts.replace(u"KEMO", u"KÍMO")
        out_nts = out_nts.replace(u"whark", u"wark")
        out_nts = out_nts.replace(u"Whark", u"Wark")
        out_nts = out_nts.replace(u"WHARK", u"WARK")
        out_nts = out_nts.replace(u"Yeeša", u"Yíša")
        out_nts = out_nts.replace(u"YEEŠA", u"YÍŠA")
    return out_nts

def ots2rts(in_ots):
    out_rts = in_ots.replace(u"ih", u"i")
    out_rts = out_rts.replace(u"Ih", u"I")
    out_rts = out_rts.replace(u"IH", u"I")
    out_rts = out_rts.replace(u"ai", u"ei")
    out_rts = out_rts.replace(u"Ai", u"Ei")
    out_rts = out_rts.replace(u"AI", u"EI")
    out_rts = out_rts.replace(u"í", u"ai")
    out_rts = out_rts.replace(u"Í", u"Ai")
    out_rts = out_rts.replace(u"ay", u"ei")
    out_rts = out_rts.replace(u"Ay", u"Ei")
    out_rts = out_rts.replace(u"AY", u"EI")
    out_rts = out_rts.replace(u"oy", u"oi")
    out_rts = out_rts.replace(u"Oy", u"Oi")
    out_rts = out_rts.replace(u"OY", u"OI")
    out_rts = out_rts.replace(u"å", u"a")
    out_rts = out_rts.replace(u"Å", u"A")
    out_rts = out_rts.replace(u"eh", u"e")
    out_rts = out_rts.replace(u"Eh", u"E")
    out_rts = out_rts.replace(u"EH", u"E")
    out_rts = out_rts.replace(u"uh", u"u")
    out_rts = out_rts.replace(u"Uh", u"U")
    out_rts = out_rts.replace(u"UH", u"U")
    if args.names:
        out_rts = out_rts.replace(u"Ae'gura", u"A'gurah")
        out_rts = out_rts.replace(u"AE'GURA", u"A'GURAH")
        out_rts = out_rts.replace(u"Ae’gura", u"A’gurah")
        out_rts = out_rts.replace(u"AE’GURA", u"A’GURAH")
        out_rts = out_rts.replace(u"Eitrus", u"Aytrus")
        out_rts = out_rts.replace(u"EITRUS", u"AYTRUS")
        out_rts = out_rts.replace(u"Atrus", u"Aytrus")
        out_rts = out_rts.replace(u"ATRUS", u"AYTRUS")
        out_rts = out_rts.replace(u"cannen", u"kanen")
        out_rts = out_rts.replace(u"Cannen", u"Kanen")
        out_rts = out_rts.replace(u"CANNEN", u"KANEN")
        out_rts = out_rts.replace(u"D'ni", u"D'nee")
        out_rts = out_rts.replace(u"D'NI", u"D'NEE")
        out_rts = out_rts.replace(u"D’ni", u"D’nee")
        out_rts = out_rts.replace(u"D’NI", u"D’NEE")
        out_rts = out_rts.replace(u"Ghen", u"Gehn")
        out_rts = out_rts.replace(u"GHEN", u"GEHN")
        out_rts = out_rts.replace(u"Er'cana", u"Ehr'kahnah")
        out_rts = out_rts.replace(u"ER'CANA", u"EHR'KAHNAH")
        out_rts = out_rts.replace(u"Er’cana", u"Ehr’kahnah")
        out_rts = out_rts.replace(u"ER’CANA", u"EHR’KAHNAH")
        out_rts = out_rts.replace(u"Kadish", u"Kaydish")
        out_rts = out_rts.replace(u"KADISH", u"KAYDISH")
        out_rts = out_rts.replace(u"Kemo", u"Keemo")
        out_rts = out_rts.replace(u"KEMO", u"KEEMO")
        out_rts = out_rts.replace(u"Minkata", u"Minkahtah")
        out_rts = out_rts.replace(u"MINKATA", u"MINKAHTAH")
        out_rts = out_rts.replace(u"Tomana", u"Tomahnah")
        out_rts = out_rts.replace(u"TOMANA", u"TOMAHNAH")
        out_rts = out_rts.replace(u"Toman", u"Tomahn")
        out_rts = out_rts.replace(u"TOMAN", u"TOMAHN")
        out_rts = out_rts.replace(u"Tsogal", u"Tsogahl")
        out_rts = out_rts.replace(u"TSOGAL", u"TSOGAHL")
        out_rts = out_rts.replace(u"whark", u"wahrk")
        out_rts = out_rts.replace(u"Whark", u"Wahrk")
        out_rts = out_rts.replace(u"WHARK", u"WAHRK")
    return out_rts

def rts2ots(in_rts):
    out_ots = in_rts.replace(u"ai", u"í")
    out_ots = out_ots.replace(u"Ai", u"Í")
    out_ots = out_ots.replace(u"AI", u"Í")
    out_ots = out_ots.replace(u"ei", u"ay")
    out_ots = out_ots.replace(u"Ei", u"Ay")
    out_ots = out_ots.replace(u"EI", u"AY")
    out_ots = out_ots.replace(u"oi", u"oy")
    out_ots = out_ots.replace(u"Oi", u"Oy")
    out_ots = out_ots.replace(u"OI", u"OY")
    out_ots = out_ots.replace(u"i", u"ih")
    out_ots = out_ots.replace(u"I", u"Ih")
    out_ots = out_ots.replace(u"e", u"eh")
    out_ots = out_ots.replace(u"E", u"Eh")
    out_ots = out_ots.replace(u"eheh", u"ee")
    out_ots = out_ots.replace(u"Eheh", u"Ee")
    out_ots = out_ots.replace(u"EhEh", u"EE")
    if args.names:
        out_ots = out_ots.replace(u"Aeh'gura", u"A'gurah")
        out_ots = out_ots.replace(u"AEh'GURA", u"A'GURAH")
        out_ots = out_ots.replace(u"Aeh’gura", u"A’gurah")
        out_ots = out_ots.replace(u"AEh’GURA", u"A’GURAH")
        out_ots = out_ots.replace(u"Ítrus", u"Aytrus")
        out_ots = out_ots.replace(u"ÍTRUS", u"AYTRUS")
        out_ots = out_ots.replace(u"Atrus", u"Aytrus")
        out_ots = out_ots.replace(u"ATRUS", u"AYTRUS")
        out_ots = out_ots.replace(u"cannehn", u"kanehn")
        out_ots = out_ots.replace(u"Cannehn", u"Kanehn")
        out_ots = out_ots.replace(u"CANNEhN", u"KANEHN")
        out_ots = out_ots.replace(u"D'ni", u"D'nee")
        out_ots = out_ots.replace(u"D'NI", u"D'NEE")
        out_ots = out_ots.replace(u"D’ni", u"D’nee")
        out_ots = out_ots.replace(u"D’NI", u"D’NEE")
        out_ots = out_ots.replace(u"Ghen", u"Gehn")
        out_ots = out_ots.replace(u"GHEN", u"GEHN")
        out_ots = out_ots.replace(u"Ehr'cana", u"Ehr'kahnah")
        out_ots = out_ots.replace(u"EHR'CANA", u"EHR'KAHNAH")
        out_ots = out_ots.replace(u"Ehr’cana", u"Ehr’kahnah")
        out_ots = out_ots.replace(u"EHR’CANA", u"EHR’KAHNAH")
        out_ots = out_ots.replace(u"Gihra", u"Girah")
        out_ots = out_ots.replace(u"GIHRA", u"GIRAH")
        out_ots = out_ots.replace(u"Kadihsh", u"Kaydish")
        out_ots = out_ots.replace(u"KADIhSH", u"KAYDISH")
        out_ots = out_ots.replace(u"Kehmo", u"Keemo")
        out_ots = out_ots.replace(u"KEhMO", u"KEEMO")
        out_ots = out_ots.replace(u"Mihnkata", u"Minkahtah")
        out_ots = out_ots.replace(u"MIHNKATA", u"MINKAHTAH")
        out_ots = out_ots.replace(u"Tolehsa", u"Tolehsah")
        out_ots = out_ots.replace(u"TOLEHSA", u"TOLEHSAH")
        out_ots = out_ots.replace(u"Tomana", u"Tomahnah")
        out_ots = out_ots.replace(u"TOMANA", u"TOMAHNAH")
        out_ots = out_ots.replace(u"Toman", u"Tomahn")
        out_ots = out_ots.replace(u"TOMAN", u"TOMAHN")
        out_ots = out_ots.replace(u"Tsogal", u"Tsogahl")
        out_ots = out_ots.replace(u"TSOGAL", u"TSOGAHL")
        out_ots = out_ots.replace(u"whark", u"wahrk")
        out_ots = out_ots.replace(u"Whark", u"Wahrk")
        out_ots = out_ots.replace(u"WHARK", u"WAHRK")
        out_ots = out_ots.replace(u"Yeesha", u"Yeeshah")
        out_ots = out_ots.replace(u"YEESHA", u"YEESHAH")
    return out_ots

def dfont2ucsur(in_dfont):
    out_ucsur = in_dfont.replace(u"v", u"")
    out_ucsur = out_ucsur.replace(u"b", u"")
    out_ucsur = out_ucsur.replace(u"t", u"")
    out_ucsur = out_ucsur.replace(u"s", u"")
    out_ucsur = out_ucsur.replace(u"S", u"")
    out_ucsur = out_ucsur.replace(u"j", u"")
    out_ucsur = out_ucsur.replace(u"g", u"")
    out_ucsur = out_ucsur.replace(u"y", u"")
    out_ucsur = out_ucsur.replace(u"K", u"")
    out_ucsur = out_ucsur.replace(u"k", u"")
    out_ucsur = out_ucsur.replace(u"a", u"")
    out_ucsur = out_ucsur.replace(u"I", u"")
    out_ucsur = out_ucsur.replace(u"f", u"")
    out_ucsur = out_ucsur.replace(u"p", u"")
    out_ucsur = out_ucsur.replace(u"i", u"")
    out_ucsur = out_ucsur.replace(u"E", u"")
    out_ucsur = out_ucsur.replace(u"e", u"")
    out_ucsur = out_ucsur.replace(u"A", u"")
    out_ucsur = out_ucsur.replace(u"r", u"")
    out_ucsur = out_ucsur.replace(u"m", u"")
    out_ucsur = out_ucsur.replace(u"T", u"")
    out_ucsur = out_ucsur.replace(u"d", u"")
    out_ucsur = out_ucsur.replace(u"D", u"")
    out_ucsur = out_ucsur.replace(u"h", u"")
    out_ucsur = out_ucsur.replace(u"o", u"")
    out_ucsur = out_ucsur.replace(u"O", u"")
    out_ucsur = out_ucsur.replace(u"c", u"")
    out_ucsur = out_ucsur.replace(u"w", u"")
    out_ucsur = out_ucsur.replace(u"u", u"")
    out_ucsur = out_ucsur.replace(u"U", u"")
    out_ucsur = out_ucsur.replace(u"x", u"")
    out_ucsur = out_ucsur.replace(u"l", u"")
    out_ucsur = out_ucsur.replace(u"å", u"")
    out_ucsur = out_ucsur.replace(u"z", u"")
    out_ucsur = out_ucsur.replace(u"n", u"")
    out_ucsur = out_ucsur.replace(u".", u"")
    out_ucsur = out_ucsur.replace(u"'", u"")
    out_ucsur = out_ucsur.replace(u"’", u"")
    out_ucsur = out_ucsur.replace(u"-", u"")
    
    out_ucsur = out_ucsur.replace(u"0", u"")
    out_ucsur = out_ucsur.replace(u"1", u"")
    out_ucsur = out_ucsur.replace(u"2", u"")
    out_ucsur = out_ucsur.replace(u"3", u"")
    out_ucsur = out_ucsur.replace(u"4", u"")
    out_ucsur = out_ucsur.replace(u"5", u"")
    out_ucsur = out_ucsur.replace(u"6", u"")
    out_ucsur = out_ucsur.replace(u"7", u"")
    out_ucsur = out_ucsur.replace(u"8", u"")
    out_ucsur = out_ucsur.replace(u"9", u"")
    out_ucsur = out_ucsur.replace(u")", u"")
    out_ucsur = out_ucsur.replace(u"!", u"")
    out_ucsur = out_ucsur.replace(u"@", u"")
    out_ucsur = out_ucsur.replace(u"#", u"")
    out_ucsur = out_ucsur.replace(u"$", u"")
    out_ucsur = out_ucsur.replace(u"%", u"")
    out_ucsur = out_ucsur.replace(u"^", u"")
    out_ucsur = out_ucsur.replace(u"&", u"")
    out_ucsur = out_ucsur.replace(u"*", u"")
    out_ucsur = out_ucsur.replace(u"(u", u"")
    out_ucsur = out_ucsur.replace(u"[", u"")
    out_ucsur = out_ucsur.replace(u"]", u"")
    out_ucsur = out_ucsur.replace(u"\\", u"")
    out_ucsur = out_ucsur.replace(u"{", u"")
    out_ucsur = out_ucsur.replace(u"}", u"")
    out_ucsur = out_ucsur.replace(u"|", u"")
    out_ucsur = out_ucsur.replace(u"=", u"")
    out_ucsur = out_ucsur.replace(u"+", u"")
    
    out_ucsur = out_ucsur.replace(u"ä", u"")
    out_ucsur = out_ucsur.replace(u"Ä", u"")
    out_ucsur = out_ucsur.replace(u"ö", u"")
    out_ucsur = out_ucsur.replace(u"Ö", u"")
    out_ucsur = out_ucsur.replace(u"ü", u"")
    out_ucsur = out_ucsur.replace(u"Ü", u"")
    out_ucsur = out_ucsur.replace(u"L", u"")
    out_ucsur = out_ucsur.replace(u"Z", u"")
    return out_ucsur

def ucsur2dfont(in_ucsur):
    out_dfont = in_ucsur.replace(u"", u"v")
    out_dfont = out_dfont.replace(u"", u"b")
    out_dfont = out_dfont.replace(u"", u"t")
    out_dfont = out_dfont.replace(u"", u"s")
    out_dfont = out_dfont.replace(u"", u"S")
    out_dfont = out_dfont.replace(u"", u"j")
    out_dfont = out_dfont.replace(u"", u"g")
    out_dfont = out_dfont.replace(u"", u"y")
    out_dfont = out_dfont.replace(u"", u"K")
    out_dfont = out_dfont.replace(u"", u"k")
    out_dfont = out_dfont.replace(u"", u"a")
    out_dfont = out_dfont.replace(u"", u"I")
    out_dfont = out_dfont.replace(u"", u"f")
    out_dfont = out_dfont.replace(u"", u"p")
    out_dfont = out_dfont.replace(u"", u"i")
    out_dfont = out_dfont.replace(u"", u"E")
    out_dfont = out_dfont.replace(u"", u"e")
    out_dfont = out_dfont.replace(u"", u"A")
    out_dfont = out_dfont.replace(u"", u"r")
    out_dfont = out_dfont.replace(u"", u"m")
    out_dfont = out_dfont.replace(u"", u"T")
    out_dfont = out_dfont.replace(u"", u"d")
    out_dfont = out_dfont.replace(u"", u"D")
    out_dfont = out_dfont.replace(u"", u"h")
    out_dfont = out_dfont.replace(u"", u"o")
    out_dfont = out_dfont.replace(u"", u"O")
    out_dfont = out_dfont.replace(u"", u"c")
    out_dfont = out_dfont.replace(u"", u"w")
    out_dfont = out_dfont.replace(u"", u"u")
    out_dfont = out_dfont.replace(u"", u"U")
    out_dfont = out_dfont.replace(u"", u"x")
    out_dfont = out_dfont.replace(u"", u"l")
    out_dfont = out_dfont.replace(u"", u"å")
    out_dfont = out_dfont.replace(u"", u"z")
    out_dfont = out_dfont.replace(u"", u"n")
    out_dfont = out_dfont.replace(u"", u".")
    out_dfont = out_dfont.replace(u"", u"'")
    out_dfont = out_dfont.replace(u"", u"’")
    out_dfont = out_dfont.replace(u"", u"-")
    
    out_dfont = out_dfont.replace(u"", u"0")
    out_dfont = out_dfont.replace(u"", u"1")
    out_dfont = out_dfont.replace(u"", u"2")
    out_dfont = out_dfont.replace(u"", u"3")
    out_dfont = out_dfont.replace(u"", u"4")
    out_dfont = out_dfont.replace(u"", u"5")
    out_dfont = out_dfont.replace(u"", u"6")
    out_dfont = out_dfont.replace(u"", u"7")
    out_dfont = out_dfont.replace(u"", u"8")
    out_dfont = out_dfont.replace(u"", u"9")
    out_dfont = out_dfont.replace(u"", u"")
    out_dfont = out_dfont.replace(u"", u"!")
    out_dfont = out_dfont.replace(u"", u"@")
    out_dfont = out_dfont.replace(u"", u"#")
    out_dfont = out_dfont.replace(u"", u"$")
    out_dfont = out_dfont.replace(u"", u"%")
    out_dfont = out_dfont.replace(u"", u"^")
    out_dfont = out_dfont.replace(u"", u"&")
    out_dfont = out_dfont.replace(u"", u"*")
    out_dfont = out_dfont.replace(u"", u"(u")
    out_dfont = out_dfont.replace(u"", u"[")
    out_dfont = out_dfont.replace(u"", u"]")
    out_dfont = out_dfont.replace(u"", u"\\")
    out_dfont = out_dfont.replace(u"", u"{")
    out_dfont = out_dfont.replace(u"", u"}")
    out_dfont = out_dfont.replace(u"", u"|")
    out_dfont = out_dfont.replace(u"", u"=")
    out_dfont = out_dfont.replace(u"", u"+")
    
    out_dfont = out_dfont.replace(u"", u"ä")
    out_dfont = out_dfont.replace(u"", u"Ä")
    out_dfont = out_dfont.replace(u"", u"ö")
    out_dfont = out_dfont.replace(u"", u"Ö")
    out_dfont = out_dfont.replace(u"", u"ü")
    out_dfont = out_dfont.replace(u"", u"Ü")
    out_dfont = out_dfont.replace(u"", u"L")
    out_dfont = out_dfont.replace(u"", u"Z")
    return out_dfont

def brack2alpha(in_brack):
    out_alpha = in_brack.replace(u"|", u"][")
    out_alpha = out_alpha.replace(u"[0]", u"0")
    out_alpha = out_alpha.replace(u"[1]", u"1")
    out_alpha = out_alpha.replace(u"[2]", u"2")
    out_alpha = out_alpha.replace(u"[3]", u"3")
    out_alpha = out_alpha.replace(u"[4]", u"4")
    out_alpha = out_alpha.replace(u"[5]", u"5")
    out_alpha = out_alpha.replace(u"[6]", u"6")
    out_alpha = out_alpha.replace(u"[7]", u"7")
    out_alpha = out_alpha.replace(u"[8]", u"8")
    out_alpha = out_alpha.replace(u"[9]", u"9")
    out_alpha = out_alpha.replace(u"[10]", u"A")
    out_alpha = out_alpha.replace(u"[11]", u"B")
    out_alpha = out_alpha.replace(u"[12]", u"C")
    out_alpha = out_alpha.replace(u"[13]", u"D")
    out_alpha = out_alpha.replace(u"[14]", u"E")
    out_alpha = out_alpha.replace(u"[15]", u"F")
    out_alpha = out_alpha.replace(u"[16]", u"G")
    out_alpha = out_alpha.replace(u"[17]", u"H")
    out_alpha = out_alpha.replace(u"[18]", u"I")
    out_alpha = out_alpha.replace(u"[19]", u"J")
    out_alpha = out_alpha.replace(u"[20]", u"K")
    out_alpha = out_alpha.replace(u"[21]", u"L")
    out_alpha = out_alpha.replace(u"[22]", u"M")
    out_alpha = out_alpha.replace(u"[23]", u"N")
    out_alpha = out_alpha.replace(u"[24]", u"O")
    out_alpha = out_alpha.replace(u"[25]", u"P")
    out_alpha = out_alpha.replace(u"[cyc]", u"X")
    out_alpha = out_alpha.replace(u"[inf]", u"§")
    out_alpha = out_alpha.replace(u"[.]", u".")
    return out_alpha

def alpha2brack(in_alpha):
    out_brack = in_alpha.replace(u"0", u"[0]")
    out_brack = out_brack.replace(u"1", u"[1]")
    out_brack = out_brack.replace(u"2", u"[2]")
    out_brack = out_brack.replace(u"3", u"[3]")
    out_brack = out_brack.replace(u"4", u"[4]")
    out_brack = out_brack.replace(u"5", u"[5]")
    out_brack = out_brack.replace(u"6", u"[6]")
    out_brack = out_brack.replace(u"7", u"[7]")
    out_brack = out_brack.replace(u"8", u"[8]")
    out_brack = out_brack.replace(u"9", u"[9]")
    out_brack = out_brack.replace(u"A", u"[10]")
    out_brack = out_brack.replace(u"B", u"[11]")
    out_brack = out_brack.replace(u"C", u"[12]")
    out_brack = out_brack.replace(u"D", u"[13]")
    out_brack = out_brack.replace(u"E", u"[14]")
    out_brack = out_brack.replace(u"F", u"[15]")
    out_brack = out_brack.replace(u"G", u"[16]")
    out_brack = out_brack.replace(u"H", u"[17]")
    out_brack = out_brack.replace(u"I", u"[18]")
    out_brack = out_brack.replace(u"J", u"[19]")
    out_brack = out_brack.replace(u"K", u"[20]")
    out_brack = out_brack.replace(u"L", u"[21]")
    out_brack = out_brack.replace(u"M", u"[22]")
    out_brack = out_brack.replace(u"N", u"[23]")
    out_brack = out_brack.replace(u"O", u"[24]")
    out_brack = out_brack.replace(u"P", u"[25]")
    out_brack = out_brack.replace(u"X", u"[cyc]")
    out_brack = out_brack.replace(u"§", u"[inf]")
    out_brack = out_brack.replace(u".", u"[.]")
    out_brack = out_brack.replace(u"][", u"|")
    return out_brack

def alpha2dfont(in_alpha):
    out_dfont = in_alpha.replace(u"A", u")")
    out_dfont = out_dfont.replace(u"B", u"!")
    out_dfont = out_dfont.replace(u"C", u"@")
    out_dfont = out_dfont.replace(u"D", u"#")
    out_dfont = out_dfont.replace(u"E", u"$")
    out_dfont = out_dfont.replace(u"F", u"%")
    out_dfont = out_dfont.replace(u"G", u"^")
    out_dfont = out_dfont.replace(u"H", u"&")
    out_dfont = out_dfont.replace(u"I", u"*")
    out_dfont = out_dfont.replace(u"J", u"(u")
    out_dfont = out_dfont.replace(u"K", u"[")
    out_dfont = out_dfont.replace(u"L", u"]")
    out_dfont = out_dfont.replace(u"M", u"\\")
    out_dfont = out_dfont.replace(u"N", u"{")
    out_dfont = out_dfont.replace(u"O", u"}")
    out_dfont = out_dfont.replace(u"P", u"|")
    out_dfont = out_dfont.replace(u"X", u"=")
    out_dfont = out_dfont.replace(u"§", u"+")
    return out_dfont

def dfont2alpha(in_dfont):
    out_alpha = in_dfont.replace(u")", u"A")
    out_alpha = out_alpha.replace(u"!", u"B")
    out_alpha = out_alpha.replace(u"@", u"C")
    out_alpha = out_alpha.replace(u"#", u"D")
    out_alpha = out_alpha.replace(u"$", u"E")
    out_alpha = out_alpha.replace(u"%", u"F")
    out_alpha = out_alpha.replace(u"^", u"G")
    out_alpha = out_alpha.replace(u"&", u"H")
    out_alpha = out_alpha.replace(u"*", u"I")
    out_alpha = out_alpha.replace(u"(u", u"J")
    out_alpha = out_alpha.replace(u"[", u"K")
    out_alpha = out_alpha.replace(u"]", u"L")
    out_alpha = out_alpha.replace(u"\\", u"M")
    out_alpha = out_alpha.replace(u"{", u"N")
    out_alpha = out_alpha.replace(u"}", u"O")
    out_alpha = out_alpha.replace(u"|", u"P")
    out_alpha = out_alpha.replace(u"=", u"X")
    out_alpha = out_alpha.replace(u"+", u"§")
    return out_alpha



if args.nts:
    nts = args.phrase.decode('utf-8')
    ots = nts2ots(nts)
    lts = nts2lts(nts)
    rts = ots2rts(ots)
    dfont = nts2dfont(nts.lower())
    ucsur = dfont2ucsur(dfont)
    print("\nOTS:     ", ots.encode('utf-8'))
    print("\nDnifont: ", dfont.encode('utf-8'))
    print("\nLTS:     ", lts.encode('utf-8'))
    print("\nRTS:     ", rts.encode('utf-8'))
    print("\nUCSUR:   ", ucsur.encode('utf-8'))

elif args.dfont:
    dfont = args.phrase.decode('utf-8')
    nts = dfont2nts(dfont)
    ots = nts2ots(nts)
    lts = nts2lts(nts)
    rts = ots2rts(ots)
    ucsur = dfont2ucsur(dfont)
    print("\nOTS:   ", ots.encode('utf-8'))
    print("\nNTS:   ", nts.encode('utf-8'))
    print("\nLTS:   ", lts.encode('utf-8'))
    print("\nRTS:   ", rts.encode('utf-8'))
    print("\nUCSUR: ", ucsur.encode('utf-8'))

elif args.lts:
    lts = args.phrase.decode('utf-8')
    nts = lts2nts(lts)
    ots = nts2ots(nts)
    rts = ots2rts(ots)
    dfont = nts2dfont(nts.lower())
    ucsur = dfont2ucsur(dfont)
    print("\nOTS:     ", ots.encode('utf-8'))
    print("\nNTS:     ", nts.encode('utf-8'))
    print("\nDnifont: ", dfont.encode('utf-8'))
    print("\nRTS:     ", rts.encode('utf-8'))
    print("\nUCSUR:   ", ucsur.encode('utf-8'))

elif args.rts:
    rts = args.phrase.decode('utf-8')
    ots = rts2ots(rts)
    nts = ots2nts(ots)
    lts = nts2lts(nts)
    dfont = nts2dfont(nts.lower())
    ucsur = dfont2ucsur(dfont)
    print("\nOTS:     ", ots.encode('utf-8'))
    print("\nNTS:     ", nts.encode('utf-8'))
    print("\nDnifont: ", dfont.encode('utf-8'))
    print("\nLTS:     ", lts.encode('utf-8'))
    print("\nUCSUR:   ", ucsur.encode('utf-8'))

elif args.ucsur:
    ucsur = args.phrase.decode('utf-8')
    dfont = ucsur2dfont(ucsur)
    nts = dfont2nts(dfont)
    ots = nts2ots(nts)
    lts = nts2lts(nts)
    rts = ots2rts(ots)
    print("\nOTS:     ", ots.encode('utf-8'))
    print("\nNTS:     ", nts.encode('utf-8'))
    print("\nDnifont: ", dfont.encode('utf-8'))
    print("\nLTS:     ", lts.encode('utf-8'))
    print("\nRTS:     ", rts.encode('utf-8'))
    
elif args.brack:
    brack = args.phrase.decode('utf-8')
    alpha = brack2alpha(brack)
    nfont = alpha2dfont(alpha)
    print("\nDnifont: ", nfont.encode('utf-8'))
    print("\nAlpha:   ", alpha.encode('utf-8'))

elif args.nfont:
    nfont = args.phrase.decode('utf-8')
    alpha = dfont2alpha(nfont)
    brack = alpha2brack(alpha)
    print("\nBrackets: ", brack.encode('utf-8'))
    print("\nAlpha:    ", alpha.encode('utf-8'))

elif args.alpha:
    alpha = args.phrase.decode('utf-8')
    brack = alpha2brack(alpha.upper())
    nfont = alpha2dfont(alpha.upper())
    print("\nDnifont:  ", nfont.encode('utf-8'))
    print("\nBrackets: ", brack.encode('utf-8'))

else:
    ots = args.phrase.decode('utf-8')
    nts = ots2nts(ots)
    dfont = nts2dfont(nts.lower())
    lts = nts2lts(nts)
    rts = ots2rts(ots)
    ucsur = dfont2ucsur(dfont)
    print("\nDnifont: ", dfont.encode('utf-8'))
    print("\nNTS:     ", nts.encode('utf-8'))
    print("\nLTS:     ", lts.encode('utf-8'))
    print("\nRTS:     ", rts.encode('utf-8'))
    print("\nUCSUR:   ", ucsur.encode('utf-8'))
