#!/usr/bin/env python3
# -*- coding: utf-8 -*-

def dniroman(dnitext, typos=True):
    dfont = dnitext.lower()
    dfont = dfont.replace(u"ch", u"c")
    dfont = dfont.replace(u"ts", u"x")
    dfont = dfont.replace(u"kh", u"k")
    dfont = dfont.replace(u"dh", u"d")
    dfont = dfont.replace(u"sh", u"S")
    dfont = dfont.replace(u"th", u"T")
    dfont = dfont.replace(u"ih", u"i")
    dfont = dfont.replace(u"ay", u"A")
    dfont = dfont.replace(u"ai", u"I")
    dfont = dfont.replace(u"ee", u"E")
    dfont = dfont.replace(u"oy", u"O")
    dfont = dfont.replace(u"oo", u"U")
    dfont = dfont.replace(u"a", u"å")
    dfont = dfont.replace(u"åh", u"a")
    dfont = dfont.replace(u"eh", u"e")
    dfont = dfont.replace(u"uh", u"u")
    if typos:
        dfont = dfont.replace(u"åe'gurå", u"å'gura")
        dfont = dfont.replace(u"aitrus", u"Atrus")
        dfont = dfont.replace(u"åtrus", u"Atrus")
        dfont = dfont.replace(u"xånnen", u"Kånen")
        dfont = dfont.replace(u"D'ni", u"D'nE")
        dfont = dfont.replace(u"ghen", u"gen")
        dfont = dfont.replace(u"er'xånå", u"er'Kana")
        dfont = dfont.replace(u"girå", u"gira")
        dfont = dfont.replace(u"jålåK", u"jalaK")
        dfont = dfont.replace(u"KåDiS", u"KADiS")
        dfont = dfont.replace(u"Kemo", u"KEmo")
        dfont = dfont.replace(u"minKåtå", u"minKata")
        dfont = dfont.replace(u"toleså", u"tolesa")
        dfont = dfont.replace(u"tomånå", u"tomana")
        dfont = dfont.replace(u"tomån", u"toman")
        dfont = dfont.replace(u"xogål", u"xogal")
        dfont = dfont.replace(u"whårK", u"warK")
        dfont = dfont.replace(u"yESå", u"yESa")
        dfont = dfont.replace(u"såmEhn", u"sameen")
        dfont = dfont.replace(u"samEhn", u"sameen")
        
        dfont = dfont.replace(u"re'rot", u"reh'rot")
        dfont = dfont.replace(u"reapo", u"rehapo")
        dfont = dfont.replace(u"rear", u"rehar")
        dfont = dfont.replace(u"reaza", u"rehaza")
        dfont = dfont.replace(u"reAvu", u"rehAvu")
        dfont = dfont.replace(u"reEbor", u"rehEbor")
        dfont = dfont.replace(u"reEK", u"rehEK")
        dfont = dfont.replace(u"reer", u"reher")
        dfont = dfont.replace(u"reev", u"rehev")
        dfont = dfont.replace(u"reoSa", u"rehoSa")
        dfont = dfont.replace(u"reUr", u"rehUr")
        dfont = dfont.replace(u"reUsatA", u"rehUsatA")
        dfont = dfont.replace(u"reUxA", u"rehUxA")
    return dfont
